# Generated by Django 6.0.3 on 2026-04-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ville',
            name='pays',
            field=models.CharField(max_length=200),
        ),
    ]
