# Generated by Django 6.0.3 on 2026-03-16 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_featured', models.BooleanField(default=False, help_text='Show this city prominently on the dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorldZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('timezone', models.CharField(help_text='Primary IANA timezone identifier, e.g. America/New_York', max_length=50)),
                ('utc_offset', models.FloatField(help_text='UTC offset in hours (e.g. -5.0 for UTC-5)')),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['continent', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('feels_like_celsius', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.IntegerField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon_code', models.CharField(blank=True, max_length=10)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshot', to='weather.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='weather.worldzone'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country_code')},
        ),
    ]
